name: "nodejs Setup"
description: "Nodejs setup action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install the Dependencies
      run: npm ci
      shell: bash