services:
  db:
    image: postgres:latest
    container_name: teaching-platform-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: teaching-platform
    ports:
      - "5431:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teaching-platform-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:pass123@db:5432/teaching-platform?schema=public"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
