name: Lint and Test
run-name: Run Lint and Tests of ${{ github.repository }} 🚀
on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: npx eslint .
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: npm run test